# Generated by Django 5.0.4 on 2024-06-14 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maps_app', '0001_initial'),
        ('users_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='users_app.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='map',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='map',
            name='users',
            field=models.ManyToManyField(related_name='allowed_maps', to=settings.AUTH_USER_MODEL, verbose_name='Разрешенные пользователи'),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='maps',
            field=models.ManyToManyField(related_name='layers', to='maps_app.map', verbose_name='Карты'),
        ),
        migrations.AddField(
            model_name='feature',
            name='map_layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='maps_app.maplayer', verbose_name='Слой'),
        ),
        migrations.AddField(
            model_name='map',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='maps_app.mapstyle', verbose_name='Стиль'),
        ),
    ]
