# Generated by Django 5.0.4 on 2024-06-15 17:16

import django.core.validators
import maps_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplayer',
            name='is_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='line_color_palette',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Цветовая палитра (JSON)'),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='line_fill_type',
            field=models.CharField(choices=[('solid', 'Сплошная'), ('value', 'От значения')], default='solid', max_length=5, verbose_name='Тип заливки'),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='line_opacity',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прозрачноть линии'),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='line_size',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Толщина линии'),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='line_solid_color',
            field=models.CharField(blank=True, default=maps_app.models.generate_random_color, max_length=7, null=True, verbose_name='Цвет сплошной заливки'),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='line_style',
            field=models.CharField(choices=[('solid', 'Сплошная'), ('dash', 'Пунктирная')], default='solid', max_length=5),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='line_value_field_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Поле для расчета'),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='point_color_palette',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Цветовая палитра (JSON)'),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='point_fill_type',
            field=models.CharField(choices=[('solid', 'Сплошная'), ('value', 'От значения')], default='solid', max_length=5, verbose_name='Тип заливки'),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='point_opacity',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прозрачноть точки'),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='point_radius',
            field=models.FloatField(default=1, verbose_name='Радиус точки'),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='point_solid_color',
            field=models.CharField(blank=True, default=maps_app.models.generate_random_color, max_length=7, null=True, verbose_name='Цвет сплошной заливки'),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='point_value_field_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Поле для расчета'),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='polygon_border_color',
            field=models.CharField(default='#000000', max_length=7, verbose_name='Цвет шрифта метки полигона'),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='polygon_border_opacity',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='polygon_border_size',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Толщина границы'),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='polygon_border_style',
            field=models.CharField(choices=[('solid', 'Сплошная'), ('dash', 'Пунктирная')], default='solid', max_length=5),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='polygon_color_palette',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Цветовая палитра (JSON)'),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='polygon_fill_type',
            field=models.CharField(choices=[('solid', 'Сплошная'), ('value', 'От значения')], default='solid', max_length=5, verbose_name='Тип заливки'),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='polygon_label',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Метка полигона'),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='polygon_label_font',
            field=models.CharField(blank=True, default='arial', max_length=256, null=True, verbose_name='Шрифт метки полигона'),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='polygon_label_font_color',
            field=models.CharField(blank=True, default='#000000', max_length=7, null=True, verbose_name='Цвет шрифта метки полигона'),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='polygon_label_font_opacity',
            field=models.PositiveIntegerField(blank=True, default=100, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прозрачность шрифта метки полигона'),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='polygon_label_font_size',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Размер шрифта метки полигона'),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='polygon_label_font_style',
            field=models.CharField(blank=True, default='medium', max_length=256, null=True, verbose_name='Стиль шрифта метки полигона'),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='polygon_opacity',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='polygon_solid_color',
            field=models.CharField(blank=True, default=maps_app.models.generate_random_color, max_length=7, null=True, verbose_name='Цвет сплошной заливки'),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='polygon_value_field_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Поле для расчета'),
        ),
    ]
