# Generated by Django 5.0.4 on 2024-06-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps_app', '0003_maplayer_is_created_maplayer_line_color_palette_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maplayer',
            name='is_created',
        ),
        migrations.AddField(
            model_name='maplayer',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
